---
- name: Copying the script to remote host
  hosts: all
  gather_facts: no
  tasks:
    - name: Copy script to remote host
      copy:
        src: /home/muhammad/ansible/ansible/service_sshd.sh
        dest: /home/user/service_sshd.sh  
        mode: '0775'  # giving this execution permission
        owner: user 
        group: user

    - name: Running the bash script on remote host
      shell: /home/user/service_sshd.sh  
      register: command_output

    - debug:
        var: command_output.stdout  
