---
- name: Copying the script to remote host
  hosts: all
  gather_facts: no
  tasks:
  - name:  copy script to remote host
    copy:
      src: /home/muhammad/ansible/ansible/
      dest: /home/user/ansible
      mode: 0775
      owner: user
      group: user
