---
- hosts: all  # all hosts you have added will be executed
  gather_facts: no # by adding this your execution will take less time
  tasks:
    - name: Copy the script and run it on remote host 
      copy:
        src: /home/muhammad/ansible/ansible/get_nginx_service.sh
        dest: /home/user/ansible/
        mode: '0755'
        owner: user
        group: user

    - name: Running script on remote host
      shell: /home/user/ansible/get_nginx_service.sh
      register: command_output

    - debug:
        var: command_output.stdout
